---
title: "Class12 Introduction to Genome Informatics Lab"
author: "Yassaman Fakhari (PID A18541145)"
format: pdf
toc: true
---

## Background 

High-throughput DNA sequencing has profoundly altered modern life science research. The
decreasing cost and increasing accessibility of these “next-generation” methods is enabling
new discoveries in diverse fields, from molecular, microbial and plant biology to disease
diagnosis, cancer biology and beyond. Here we address these critical barriers with an accessible
introduction to a set of freely available cloud-based genomics analysis tools and databases. In
this lesson, students will learn to use the ENSEMBLE and OMIM databases, together with the
Galaxy suite of bioinformatics tools, to investigate genomics, transcriptomics and population
variability in the context of childhood asthma.

## Section 1: Identify genetic variants of interest

There are a number of gene variants associated with childhood asthma. A study from Verlaan
et al. (2009) shows that 4 candidate SNPs demonstrate significant evidence for association.
You want to find out what they are by visiting OMIM (http://www.omim.org) and locating the
Verlaan et al. paper description.

> Q1: What are those 4 candidate SNPs?

4 candidate SNPs (rs12936231, rs8067378, rs9303277, and rs7216389)

> Q2: What three genes do these variants overlap or effect?

The OMIM entry states that the variants are involved in “domainwide cis-regulation involving ZPBP2, GSDMB, and ORMDL3.”

> Q3: What is the location of rs8067378 and what are the different alleles for rs8067378?

Location: 17:39,894,595-39,895,595, allese: A/C/G|Ancestral: G

> Q4: Name at least 3 downstream genes for rs8067378? 

GSDMB, ORMDL3, IKZF3

> Q5: What proportion of the Mexican Ancestry in Los Angeles sample population (MXL) are
homozygous for the asthma associated SNP (G|G)?

9 out of 64 individuals in the MXL population were homozygous for the asthma-associated SNP (G|G), which is approximately 14.1%.

> Q6. Back on the ENSEMBLE page, use the “search for a sample” field above to find the
particular sample HG00109. This is a male from the GBR population group. What is the
genotype for this sample?

G|G

## Section 2: Initial RNA-Seq analysis

Now, you want to understand whether the SNP will affect gene expression. You can find the
raw RNA-Seq data of this one sample on the class webpage:
https://bioboot.github.io/bggn213_W19/class-material/HG00109_1.fastq
https://bioboot.github.io/bggn213_W19/class-material/HG00109_2.fastq

> Q7: How many sequences are there in the first file? What is the file size and format of the data?

Number of sequences in the first file: 3,863 sequences
File size: 	741.9 KB
Format: FASTQ (fastqsanger)

> Q8: What is the GC content and sequence length of the second fastq file?

GC content is 54 % and the sequence length is 3863

> Q9: How about per base sequence quality? Does any base have a mean quality score below
20?

No, none of the bases have a mean quality score below 20. Therefore, trimming is not necessary for this dataset.

## Section 3: Mapping RNA-Seq reads to genome

The next step is mapping the processed reads to the genome. The major challenge when
mapping RNA-Seq reads is that the reads, because they come from RNA, often cross splice
junction boundaries; splice junctions are not present in a genome's sequence, and hence
typical NGS mappers such as Bowtie (http://bowtie-bio.sourceforge.net/index.shtml ) and
BWA (http://bio-bwa.sourceforge.net/ ) are not ideal without modifying the genome sequence.
Instead, it is better to use a mapper such as Tophat (http://ccb.jhu.edu/software/tophat) that is
designed to map RNA-seq reads.

> Q10: Where are most the accepted hits located?

Most of the accepted hits are located around the ORMDL3 and GSDMB gene region on chromosome 17.

> Q11: Following Q10, is there any interesting gene around that area?

One interesting gene around this region is ORMDL3, which has previously been associated with childhood asthma susceptibility.

> Q12: Cufflinks again produces multiple output files that you can inspect from your right-handside galaxy history. From the “gene expression” output, what is the FPKM for the ORMDL3
gene? What are the other genes with above zero FPKM values?

The FPKM value for the ORMDL3 gene is approximately 127.6. Other genes with above-zero FPKM values includes GSDMB, ZPBP2, and IKZF3. These genes are all located near the asthma-associated SNP region on chromosome 17q21.






